# Generated by Django 6.0 on 2025-12-16 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_needed', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('passport', 'Passport Processing'), ('visa', 'Visa Processing'), ('air_ticket', 'Air Ticketing'), ('car_hire', 'Car Hire'), ('honeymoon', 'Honeymoon Packages'), ('interpol', 'Interpol Services'), ('national_id', 'National IDs'), ('tour', 'Tour Packages')], max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List requirements separated by commas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_time', models.CharField(help_text='e.g., 3-5 working days', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_location', models.CharField(blank=True, max_length=100)),
                ('client_avatar_url', models.URLField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('safari', 'Safari Adventure'), ('honeymoon', 'Honeymoon Package'), ('beach', 'Beach Trip'), ('cultural', 'Cultural Excursion'), ('custom', 'Custom Itinerary')], max_length=50)),
                ('description', models.TextField()),
                ('overview', models.TextField(help_text='Brief overview for listings')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('max_people', models.PositiveIntegerField()),
                ('itinerary', models.TextField(help_text='Day-by-day itinerary')),
                ('includes', models.TextField(help_text="What's included, separated by commas")),
                ('excludes', models.TextField(help_text="What's not included, separated by commas")),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('booking_details', models.TextField(blank=True, help_text='Additional requirements/notes')),
                ('number_of_travelers', models.PositiveIntegerField(default=1)),
                ('travel_dates', models.CharField(blank=True, help_text='Preferred travel dates', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.service')),
                ('tour_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tourpackage')),
            ],
        ),
    ]
